### ISSUE TITLE
Knobs are not allowed to go to full scale rotation.

### ISSUE THREAD

**Issue by ising4jesus** [ColinBD/JSAudioKnobs#2]
The starting number and rotation are fine, however...

The knobs will only rotate to about 99%.
The numbers still go to the top value, but the rotation of the nob does not.
This is easiest to see on the Vintage knobs, but all of them appear to have the same problem.
See attached images.
![Hippy](https://user-images.githubusercontent.com/44988876/83262099-0599b000-a182-11ea-9215-cedd86553f87.png)
![Aqua](https://user-images.githubusercontent.com/44988876/83262102-06324680-a182-11ea-864f-b45d6e131f5f.png)
![FStyle](https://user-images.githubusercontent.com/44988876/83262104-06324680-a182-11ea-9100-78891d2c43f4.png)
![Vintage](https://user-images.githubusercontent.com/44988876/83262107-06cadd00-a182-11ea-8e51-33e51e1b4ec1.png)
![kjLED](https://user-images.githubusercontent.com/44988876/83262109-07637380-a182-11ea-9007-de00a63c2de3.png)

**Comment by ising4jesus** [comment]
I checked the graphic images included.  
The 100% images do exist, but the code is not allowing them to display.

**Comment by ColinBD** [comment]
Thanks for reporting the issue. It should now be fixed.

**Comment by ising4jesus** [comment]
Thanks Colin!


I'd thought about fixing it myself, but I didn't have the time to work on it.


Thank you!  I'll check out the updated code.



- Brian
